spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://dpg-d0p102emcj7s73dm9jb0-a.oregon-postgres.render.com:5432/super_mobility?sslmode=require
spring.datasource.username=super_mobility_user
spring.datasource.password=lJt9q7Xlko8bebTK15Zpo39leC6F351k
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update